import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../data/database.dart';

String money(num x)=>NumberFormat.currency(locale:'en_IN',symbol:'₹',decimalDigits:2).format(x);

class AppShell extends StatefulWidget{const AppShell({super.key});@override State<AppShell> createState()=>_AppShellState();}
class _AppShellState extends State<AppShell>{int index=0;final pages=const[Dashboard(),Products(),Billing(),Customers(),More()];@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:pages[index]),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(x)=>setState(()=>index=x),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),label:'Products'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),label:'Billing'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Customers'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'More')]));}

class Dashboard extends StatefulWidget{const Dashboard({super.key});@override State<Dashboard> createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{Map<String,Object?> data={};@override void initState(){super.initState();load();}Future<void>load()async{if(!AppDatabase.instance.initialized)return;data=await AppDatabase.instance.dashboard();if(mounted)setState((){});}Widget stat(String a,String b,IconData i)=>SizedBox(width:190,child:Card(child:ListTile(leading:Icon(i),title:Text(a),subtitle:Text(b,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)))));@override Widget build(BuildContext c)=>RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[Text('Dashboard',style:Theme.of(c).textTheme.headlineMedium),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[stat('Today sales',money((data['sales'] as num?)??0),Icons.payments),stat('Bills',(data['bills']??0).toString(),Icons.receipt),stat('Expenses',money((data['expenses'] as num?)??0),Icons.money_off),stat('Low stock',(data['low']??0).toString(),Icons.warning),stat('Customer due',money((data['due'] as num?)??0),Icons.credit_card)]),const SizedBox(height:16),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ProductForm())),icon:const Icon(Icons.add_box),label:const Text('Add product'))]));}

class Products extends StatefulWidget{const Products({super.key});@override State<Products> createState()=>_ProductsState();}
class _ProductsState extends State<Products>{final q=TextEditingController();List<Map<String,Object?>> rows=[];bool low=false;@override void initState(){super.initState();load();}Future<void>load()async{rows=await AppDatabase.instance.products(q:q.text,low:low);if(mounted)setState((){});} @override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:Text('Products',style:Theme.of(c).textTheme.headlineMedium)),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ProductForm())).then((_){load();}),icon:const Icon(Icons.add))])),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:TextField(controller:q,onChanged:(_)=>load(),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Name, SKU or barcode',border:OutlineInputBorder()))),SwitchListTile(title:const Text('Low stock only'),value:low,onChanged:(v){low=v;load();}),Expanded(child:rows.isEmpty?const Center(child:Text('No products yet.')):ListView.builder(itemCount:rows.length,itemBuilder:(_,i){final p=rows[i];return ListTile(title:Text(p['name'].toString()),subtitle:Text('SKU '+p['sku'].toString()+' • Stock '+p['stock'].toString()),trailing:Text(money(p['selling_price'] as num)));}))]);}

class ProductForm extends StatefulWidget{const ProductForm({super.key});@override State<ProductForm> createState()=>_ProductFormState();}
class _ProductFormState extends State<ProductForm>{final name=TextEditingController(),sku=TextEditingController(),barcode=TextEditingController(),buy=TextEditingController(),sell=TextEditingController(),stock=TextEditingController(),min=TextEditingController();Widget field(TextEditingController x,String label)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));Future<void>save()async{if(name.text.trim().isEmpty||sku.text.trim().isEmpty)return;try{await AppDatabase.instance.saveProduct({'name':name.text.trim(),'sku':sku.text.trim(),'barcode':barcode.text.trim().isEmpty?null:barcode.text.trim(),'purchase_price':double.tryParse(buy.text)??0,'selling_price':double.tryParse(sell.text)??0,'stock':double.tryParse(stock.text)??0,'min_stock':double.tryParse(min.text)??0,'unit':'pcs'});if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Add product')),body:ListView(padding:const EdgeInsets.all(16),children:[field(name,'Product name'),field(sku,'SKU'),field(barcode,'Barcode'),field(buy,'Purchase price'),field(sell,'Selling price'),field(stock,'Opening stock'),field(min,'Minimum stock'),FilledButton(onPressed:save,child:const Text('Save product'))]));}

class Billing extends StatefulWidget{const Billing({super.key});@override State<Billing> createState()=>_BillingState();}
class _BillingState extends State<Billing>{final q=TextEditingController();List<Map<String,Object?>> products=[];final cart=<Map<String,Object?>>[];@override void initState(){super.initState();search();}Future<void>search()async{products=await AppDatabase.instance.products(q:q.text);if(mounted)setState((){});}void add(Map<String,Object?> p){final rate=(p['selling_price'] as num).toDouble();cart.add({'productId':p['id'],'name':p['name'],'qty':1.0,'rate':rate,'total':rate});setState((){});}double get total=>cart.fold(0,(a,x)=>a+(x['total'] as double));Future<void>checkout()async{if(cart.isEmpty)return;try{await AppDatabase.instance.completeSale(cart);cart.clear();await search();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sale saved offline.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Text('Billing / POS',style:Theme.of(c).textTheme.headlineMedium)),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:TextField(controller:q,onChanged:(_)=>search(),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search product',border:OutlineInputBorder()))),SizedBox(height:100,child:ListView.builder(scrollDirection:Axis.horizontal,itemCount:products.length,itemBuilder:(_,i)=>SizedBox(width:180,child:Card(child:ListTile(title:Text(products[i]['name'].toString()),subtitle:Text('Stock '+products[i]['stock'].toString()),onTap:()=>add(products[i])))))),Expanded(child:ListView(children:cart.map((x)=>ListTile(title:Text(x['name'].toString()),subtitle:Text('Qty '+x['qty'].toString()),trailing:Text(money(x['total'] as num)))).toList())),Padding(padding:const EdgeInsets.all(12),child:FilledButton.icon(onPressed:checkout,icon:const Icon(Icons.check),label:Text('Complete sale • '+money(total))))]);}

class Customers extends StatefulWidget{const Customers({super.key});@override State<Customers> createState()=>_CustomersState();}
class _CustomersState extends State<Customers>{final q=TextEditingController();List<Map<String,Object?>> rows=[];@override void initState(){super.initState();load();}Future<void>load()async{rows=await AppDatabase.instance.customers(q.text);if(mounted)setState((){});}Future<void>add()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const CustomerForm()));load();}@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:Text('Customers',style:Theme.of(c).textTheme.headlineMedium)),IconButton(onPressed:add,icon:const Icon(Icons.add))])),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:TextField(controller:q,onChanged:(_)=>load(),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Name or phone',border:OutlineInputBorder()))),Expanded(child:ListView.builder(itemCount:rows.length,itemBuilder:(_,i)=>ListTile(title:Text(rows[i]['name'].toString()),subtitle:Text(rows[i]['phone'].toString()),trailing:Text(money((rows[i]['due'] as num?)??0)))))]);}
class CustomerForm extends StatefulWidget{const CustomerForm({super.key});@override State<CustomerForm> createState()=>_CustomerFormState();}
class _CustomerFormState extends State<CustomerForm>{final n=TextEditingController(),p=TextEditingController();@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Add customer')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:p,decoration:const InputDecoration(labelText:'Phone',border:OutlineInputBorder())),const SizedBox(height:15),FilledButton(onPressed:()async{if(n.text.trim().isEmpty)return;await AppDatabase.instance.saveCustomer({'name':n.text.trim(),'phone':p.text.trim(),'address':'','notes':''});if(mounted)Navigator.pop(context);},child:const Text('Save customer'))]));}

class More extends StatelessWidget{const More({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('More',style:Theme.of(c).textTheme.headlineMedium),ListTile(leading:const Icon(Icons.money_off),title:const Text('Expenses'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ExpenseForm()))),ListTile(leading:const Icon(Icons.bar_chart),title:const Text('Reports'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Reports()))),ListTile(leading:const Icon(Icons.settings),title:const Text('Settings'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Settings())))]);}
class ExpenseForm extends StatefulWidget{const ExpenseForm({super.key});@override State<ExpenseForm> createState()=>_ExpenseFormState();}
class _ExpenseFormState extends State<ExpenseForm>{final amount=TextEditingController(),desc=TextEditingController();@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Expense')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:desc,decoration:const InputDecoration(labelText:'Description',border:OutlineInputBorder())),const SizedBox(height:15),FilledButton(onPressed:()async{final v=double.tryParse(amount.text);if(v==null||v<=0)return;await AppDatabase.instance.addExpense(v,'Miscellaneous',desc.text);if(mounted)Navigator.pop(context);},child:const Text('Save expense'))]));}
class Reports extends StatelessWidget{const Reports({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Reports')),body:FutureBuilder<Map<String,Object?>>(future:AppDatabase.instance.dashboard(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=s.data!;return ListView(padding:const EdgeInsets.all(16),children:[Text('Today sales: '+money(d['sales'] as num)),Text('Bills: '+d['bills'].toString()),Text('Expenses: '+money(d['expenses'] as num)),Text('Customer dues: '+money(d['due'] as num))]);}));}}
class Settings extends StatefulWidget{const Settings({super.key});@override State<Settings> createState()=>_SettingsState();}
class _SettingsState extends State<Settings>{final shop=TextEditingController();@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Settings')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:shop,decoration:const InputDecoration(labelText:'Shop name',border:OutlineInputBorder())),const SizedBox(height:12),FilledButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Saved locally.'))),child:const Text('Save')),const SizedBox(height:20),const Text('SQLite is the primary database. Normal shop operations do not require internet or an account.')]));}}
