import{useEffect,useMemo,useState}from"react";import{Customer,Product,Sale,State,exportState,importState,id,load,money,save}from"./db";
type Tab="home"|"products"|"billing"|"sales"|"customers"|"reports"|"settings";
const blankProduct=():Product=>({id:id(),name:"",sku:"",barcode:"",category:"",buy:0,sell:0,stock:0,minStock:0,unit:"pcs",createdAt:Date.now(),updatedAt:Date.now()});
export default function App(){const[s,setS]=useState<State|null>(null);const[tab,setTab]=useState<Tab>("home");const[q,setQ]=useState("");const[cart,setCart]=useState<{p:Product;qty:number}[]>([]);const[customer,setCustomer]=useState("");const[payment,setPayment]=useState<Sale["payment"]>("Cash");const[discount,setDiscount]=useState(0);
useEffect(()=>{load().then(setS)},[]);if(!s)return <div className="loading">Loading Sinvo…</div>;
const persist=async(n:State)=>{setS(n);await save(n)};const products=s.products.filter(p=>(p.name+" "+p.sku+" "+p.barcode+" "+p.category).toLowerCase().includes(q.toLowerCase()));const revenue=s.sales.reduce((a,x)=>a+x.total,0);const stockValue=s.products.reduce((a,p)=>a+p.stock*p.buy,0);const low=s.products.filter(p=>p.stock<=p.minStock).length;
function addProduct(){const p=blankProduct();const n=prompt("Product name");if(!n)return;p.name=n;const sell=Number(prompt("Selling price","0")||0);const buy=Number(prompt("Purchase price","0")||0);const qty=Number(prompt("Opening stock","0")||0);p.sell=sell;p.buy=buy;p.stock=qty;persist({...s,products:[...s.products,p]})}
function adjust(p:Product){const n=Number(prompt("Set stock quantity",String(p.stock)));if(Number.isFinite(n)&&n>=0)persist({...s,products:s.products.map(x=>x.id===p.id?{...x,stock:n,updatedAt:Date.now()}:x)})}
function addCart(p:Product){setCart(c=>{const e=c.find(x=>x.p.id===p.id);return e?c.map(x=>x.p.id===p.id?{...x,qty:Math.min(p.stock,x.qty+1)}:x):[...c,{p,qty:1}]})}
const subtotal=cart.reduce((a,x)=>a+x.qty*x.p.sell,0),total=Math.max(0,subtotal-discount);
function checkout(){if(!cart.length)return;for(const x of cart)if(x.qty>x.p.stock)return alert("Insufficient stock: "+x.p.name);const c=s.customers.find(x=>x.id===customer);const inv=(s.settings.prefix||"INV")+"-"+String(s.sales.length+1).padStart(5,"0");const sale:Sale={id:id(),invoice:inv,customerId:c?.id||"",customerName:c?.name||"Walk-in",payment,items:cart.map(x=>({productId:x.p.id,name:x.p.name,qty:x.qty,price:x.p.sell})),subtotal,discount,total,createdAt:Date.now()};const products=s.products.map(p=>{const x=cart.find(x=>x.p.id===p.id);return x?{...p,stock:p.stock-x.qty,updatedAt:Date.now()}:p});const customers=s.customers.map(x=>x.id===c?.id&&payment==="Credit"?{...x,due:x.due+total}:x);persist({...s,products,customers,sales:[...s.sales,sale]});setCart([]);setDiscount(0);alert("Saved "+inv)}
async function restore(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{setS(await importState(f).then(async x=>{await save(x);return x}))}catch{alert("Invalid backup file")}}
return <div className="app"><header><div><b className="brand">SINVO</b><span className="sub">Offline Shop Manager</span></div><button className="icon" onClick={()=>setTab("settings")}>⚙</button></header>
<nav>{(["home","products","billing","sales","customers","reports","settings"] as Tab[]).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
<main>{tab==="home"&&<><section className="hero"><div><small>Today</small><h1>{money(revenue,s.settings.currency)}</h1><span>Sales revenue</span></div><div className="heroStat"><b>{s.products.length}</b><span>Products</span></div><div className="heroStat"><b>{low}</b><span>Low stock</span></div></section><div className="grid"><Card t="Stock value" v={money(stockValue,s.settings.currency)}/><Card t="Invoices" v={String(s.sales.length)}/><Card t="Customer due" v={money(s.customers.reduce((a,c)=>a+c.due,0),s.settings.currency)}/></div><h2>Quick actions</h2><div className="actions"><button onClick={()=>setTab("billing")}>New Bill</button><button onClick={()=>{setTab("products");addProduct()}}>Add Product</button><button onClick={()=>setTab("products")}>Search Stock</button></div></>}
{tab==="products"&&<><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, SKU, barcode, category…"/><button onClick={addProduct}>+ Product</button></div><div className="list">{products.map(p=><article className="row"><div><b>{p.name||"Unnamed"}</b><small>{p.sku||"No SKU"} {p.barcode&&"· "+p.barcode}</small></div><div className="price">{money(p.sell,s.settings.currency)}<small>Buy {money(p.buy,s.settings.currency)}</small></div><div className={p.stock<=p.minStock?"stock low":"stock"}>{p.stock} {p.unit}</div><button onClick={()=>adjust(p)}>Stock</button></article>)}{!products.length&&<Empty text="No products found"/>}</div></>}
{tab==="billing"&&<><div className="billing"><div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find product to add…"/></div><div className="list compact">{products.map(p=><button className="productPick" disabled={!p.stock} onClick={()=>addCart(p)}><span><b>{p.name}</b><small>{p.stock} in stock</small></span><strong>{money(p.sell,s.settings.currency)}</strong></button>)}</div></div><aside className="cart"><h2>Current Bill</h2>{cart.map(x=><div className="cartRow"><span>{x.p.name} × {x.qty}</span><b>{money(x.qty*x.p.sell,s.settings.currency)}</b></div>)}<div className="formline"><label>Customer</label><select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Walk-in</option>{s.customers.map(c=><option value={c.id}>{c.name}</option>)}</select></div><div className="formline"><label>Payment</label><select value={payment} onChange={e=>setPayment(e.target.value as Sale["payment"])}><option>Cash</option><option>UPI</option><option>Card</option><option>Credit</option></select></div><div className="formline"><label>Discount</label><input type="number" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></div><div className="total"><span>Total</span><b>{money(total,s.settings.currency)}</b></div><button className="primary" onClick={checkout}>Complete Bill</button></aside></div></>}
{tab==="sales"&&<><h2>Sales</h2><div className="list">{s.sales.slice().reverse().map(x=><article className="row"><div><b>{x.invoice}</b><small>{x.customerName} · {x.payment}</small></div><div><b>{money(x.total,s.settings.currency)}</b><small>{new Date(x.createdAt).toLocaleString()}</small></div></article>)}{!s.sales.length&&<Empty text="No sales yet"/>}</div></>}
{tab==="customers"&&<Customers s={s} persist={persist}/>}
{tab==="reports"&&<><h2>Reports</h2><div className="grid"><Card t="Revenue" v={money(revenue,s.settings.currency)}/><Card t="Purchases" v={money(s.purchases.reduce((a,x)=>a+x.total,0),s.settings.currency)}/><Card t="Gross margin" v={money(s.sales.reduce((a,x)=>a+x.items.reduce((z,i)=>{const p=s.products.find(p=>p.id===i.productId);return z+i.qty*(i.price-(p?.buy||0))},0),0)-discount,s.settings.currency)}/></div><div className="panel"><b>Low stock</b>{s.products.filter(p=>p.stock<=p.minStock).map(p=><p>{p.name}: {p.stock} remaining</p>)}</div></>}
{tab==="settings"&&<Settings s={s} persist={persist} restore={restore}/>}</main></div>}
function Card({t,v}:{t:string;v:string}){return <div className="card"><small>{t}</small><b>{v}</b></div>}function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Customers({s,persist}:{s:State;persist:(n:State)=>Promise<void>}){function add(){const name=prompt("Customer name");if(!name)return;const phone=prompt("Phone","")||"";const c:Customer={id:id(),name,phone,due:0,createdAt:Date.now()};persist({...s,customers:[...s.customers,c]})}return <><div className="toolbar"><h2>Customers</h2><button onClick={add}>+ Customer</button></div><div className="list">{s.customers.map(c=><article className="row"><div><b>{c.name}</b><small>{c.phone||"No phone"}</small></div><strong>{money(c.due,s.settings.currency)} due</strong></article>)}{!s.customers.length&&<Empty text="No customers yet"/>}</div></>}
function Settings({s,persist,restore}:{s:State;persist:(n:State)=>Promise<void>;restore:(e:React.ChangeEvent<HTMLInputElement>)=>void}){const[x,setX]=useState(s.settings);return <div className="panel settings"><h2>Shop settings</h2>{(["shop","phone","address","currency","prefix"] as const).map(k=><label>{k}<input value={x[k]} onChange={e=>setX({...x,[k]:e.target.value})}/></label>)}<button className="primary" onClick={()=>persist({...s,settings:x})}>Save settings</button><hr/><button onClick={()=>exportState(s)}>Export local backup</button><label className="file">Import backup<input type="file" accept=".json,application/json" onChange={restore}/></label><p className="muted">No account, server, cloud database or login. Your shop data stays on this device/browser.</p></div>}