export type Product={id:string;name:string;brand:string;model:string;sku:string;barcode:string;category:string;buy:number;sell:number;stock:number;minStock:number;unit:string;createdAt:number;updatedAt:number};
export type SaleItem={productId:string;name:string;qty:number;price:number};
export type Sale={id:string;invoice:string;payment:"Cash"|"UPI"|"Card";items:SaleItem[];subtotal:number;discount:number;total:number;createdAt:number};
export type PurchaseItem={productId:string;qty:number;cost:number};
export type Purchase={id:string;supplier:string;invoice:string;items:PurchaseItem[];total:number;createdAt:number};
export type State={products:Product[];sales:Sale[];purchases:Purchase[];settings:{shop:string;phone:string;address:string;currency:string;prefix:string}};
const KEY="sinvo-state-v2";const empty:State={products:[],sales:[],purchases:[],settings:{shop:"My Shop",phone:"",address:"",currency:"₹",prefix:"INV"}};
const clone=<T,>(x:T):T=>structuredClone(x);let memory:State|null=null;
function normalize(x:any):State{const base:any=clone(empty);Object.assign(base,x||{});base.products=Array.isArray(base.products)?base.products.map((p:any)=>({...p,brand:typeof p.brand==="string"?p.brand:"",model:typeof p.model==="string"?p.model:""})):[];base.sales=Array.isArray(base.sales)?base.sales:[];base.purchases=Array.isArray(base.purchases)?base.purchases:[];base.settings={...empty.settings,...(x?.settings||{})};base.sales=base.sales.map((sale:any)=>({...sale,payment:sale.payment==="Credit"?"Cash":sale.payment}));return base}
function idb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const o=indexedDB.open("sinvo",2);o.onupgradeneeded=()=>{if(!o.result.objectStoreNames.contains("state"))o.result.createObjectStore("state")};o.onsuccess=()=>resolve(o.result);o.onerror=()=>reject(o.error)})}
export async function load():Promise<State>{if(memory)return clone(memory);if(!("indexedDB"in window)){try{const raw=localStorage.getItem(KEY)||localStorage.getItem("sinvo-state-v1");memory=normalize(raw?JSON.parse(raw):empty)}catch{memory=clone(empty)}return clone(memory)}
try{const db=await idb();const tx=db.transaction("state","readonly");const r=tx.objectStore("state").get("main");const v=await new Promise<any>((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});memory=normalize(v?JSON.parse(v):empty);return clone(memory)}catch{memory=clone(empty);return clone(memory)}}
export async function save(s:State){memory=normalize(s);if(!("indexedDB"in window)){localStorage.setItem(KEY,JSON.stringify(memory));return}const db=await idb();const tx=db.transaction("state","readwrite");tx.objectStore("state").put(JSON.stringify(memory),"main");await new Promise<void>((ok,no)=>{tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error)})}
export function id(){return crypto.randomUUID()}export function money(n:number,c="₹"){return c+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
export function exportState(s:State){const b=new Blob([JSON.stringify(s,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="sinvo-backup.json";a.click();URL.revokeObjectURL(a.href)}
export function importState(file:File):Promise<State>{return file.text().then(t=>{const x=JSON.parse(t);if(!x.products||!x.sales||!x.settings)throw Error("Invalid Sinvo backup");return normalize(x)})}